export const RETRIEVE_MOVIES_GENRES_SUCCESS = 'RETRIEVE_MOVIES_GENRES_SUCCESS';

export const RETRIEVE_POPULAR_MOVIES_SUCCESS = 'RETRIEVE_POPULAR_MOVIES_SUCCESS';
export const RETRIEVE_NOWPLAYING_MOVIES_SUCCESS = 'RETRIEVE_NOWPLAYING_MOVIES_SUCCESS';
export const RETRIEVE_MOVIES_LIST_SUCCESS = 'RETRIEVE_MOVIES_LIST_SUCCESS';
export const RETRIEVE_BOOK_DETAILS_SUCCESS = 'RETRIEVE_BOOK_DETAILS_SUCCESS';
export const RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS = 'RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS';


export const RETRIEVE_POPULAR_BOOKS_SUCCESS = 'RETRIEVE_POPULAR_BOOKS_SUCCESS';
export const RETRIEVE_BOOK_PRICES_SUCCESS = 'RETRIEVE_BOOK_PRICES_SUCCESS';
export const RETRIEVE_AUTHOR_BOOKS_SUCCESS = 'RETRIEVE_AUTHOR_BOOKS_SUCCESS';

export const RETRIEVE_BOOKS_SEARCH_RESULT_SUCCESS = 'RETRIEVE_BOOKS_SEARCH_RESULT_SUCCESS';
export const RETRIEVE_POPULAR_AUTHORS_SUCCESS = 'RETRIEVE_POPULAR_AUTHORS_SUCCESS';